#!/bin/bash
# Created 2021-06-28
# Bash-Moduls by Thomas Pautler
#  ______      ____
# /_  __/___  / __ \____ _      __
#  / / / __ \/ /_/ / __ \ | /| / /
# / / / /_/ / ____/ /_/ / |/ |/ /
#/_/  \____/_/    \____/|__/|__/
#
print_l() {
     [[ $# == 0 ]] && return 1

     declare -i TERM_COLS="$(tput cols)"
     declare -i str_len="${#1}"
     [[ $str_len -ge $TERM_COLS ]] && {
          echo "$1";
          return 0;
     }

     declare -i filler_len="$(( (TERM_COLS - str_len) / 2 ))"
     [[ $# -ge 2 ]] && ch="${2:0:1}" || ch=" "
     filler=""
     for (( i = 0; i < filler_len; i++ )); do
          filler="${filler}${ch}"
     done

     printf "%s%s%s" "$1" "$filler" "$filler"
     [[ $(( (TERM_COLS - str_len) % 2 )) -ne 0 ]] && printf "%s" "${ch}"
     printf "\n"

     return 0
}

print_c() {
     [[ $# == 0 ]] && return 1

     declare -i TERM_COLS="$(tput cols)"
     declare -i str_len="${#1}"
     [[ $str_len -ge $TERM_COLS ]] && {
          echo "$1";
          return 0;
     }

     declare -i filler_len="$(( (TERM_COLS - str_len) / 2 ))"
     [[ $# -ge 2 ]] && ch="${2:0:1}" || ch=" "
     filler=""
     for (( i = 0; i < filler_len; i++ )); do
          filler="${filler}${ch}"
     done

     printf "%s%s%s" "$filler" "$1" "$filler"
     [[ $(( (TERM_COLS - str_len) % 2 )) -ne 0 ]] && printf "%s" "${ch}"
     printf "\n"

     return 0
}

print_r() {
     [[ $# == 0 ]] && return 1

     declare -i TERM_COLS="$(tput cols)"
     declare -i str_len="${#1}"
     [[ $str_len -ge $TERM_COLS ]] && {
          echo "$1";
          return 0;
     }

     declare -i filler_len="$(( (TERM_COLS - str_len) / 2 ))"
     [[ $# -ge 2 ]] && ch="${2:0:1}" || ch=" "
     filler=""
     for (( i = 0; i < filler_len; i++ )); do
          filler="${filler}${ch}"
     done

     printf "%s%s%s" "$filler" "$filler" "$1"
     [[ $(( (TERM_COLS - str_len) % 2 )) -ne 0 ]] && printf "%s" "${ch}"
     printf "\n"

     return 0
}

print_mlbc() {
    local longest=0
    local string_array=("${@}")
    for i in "${string_array[@]}"; do
      if [[ "${#i}" -gt "${longest}" ]]; then
        local longest=${#i}
        local longest_line="${i}" # Longest line
      fi
    done
  
    local edge=$(echo "$longest_line" | sed 's/./━/g' | sed 's/^/━/' | sed 's/$/━/')
    local middle_edge=$(echo "$longest_line" | sed 's/./\ /g' | sed 's/^\ /┃\  /' | sed 's/\ $/\ \ ┃/')
  
    print_c "${edge}"
    print_c "${middle_edge}"
  
    for i in "${string_array[@]}"; do
      local length_i=${#i}
      local length_ll="${#longest_line}"
     short_l=`if [[ "${length_i}" -lt "${length_ll}"  ]]; then
              printf "┃ "
              local remaining_spaces=$((length_ll-length_l))
              printf "${i}"
              while [[ ${remaining_spaces} -gt ${#i} ]]; do
                      printf " "
                      local remaining_spaces=$((remaining_spaces-1))
              done
              printf " ┃\n"
      else
        echo "┃ ${i} ┃"
      fi`
      print_c "$short_l"
    done
     
    print_c "${middle_edge}"
    print_c "${edge}"
}


banner() {
    msg="$1 $2 $1"
    edge=$(echo "$msg" | sed "s/./$1/g")
    echo "$edge"
    echo "$msg"
    echo "$edge"
}

banner_c() {
    msg="$1 $2 $1"
    edge=$(echo "$msg" | sed "s/./$1/g")
    print_c "$edge"
    print_c "$msg"
    print_c "$edge"
}

banner_r() {
    msg="$1 $2 $1"
    edge=$(echo "$msg" | sed "s/./$1/g")
    print_r "$edge"
    print_r "$msg"
    print_r "$edge"
}

numlist() {
	LIST="$1"
	TITLE="$3"
	LINE="$4"
	LSTYL="${LINE:-━}"
	print_c "$TITLE" "$LSTYL"
	PS3=$(print_c "$LSTYL" "$LSTYL" ; echo "$2")
	select RV in ${LIST}; do
		return
	done
}

#LI=$(ls --group-directories-first ${HOME})
#numlist "$LI" "Please select: " " This is your Home Dir " 
#echo
#echo "$RV"


multilist() {
	LIST="$1"
	TITLE="$3"
	LINE="$4"
	LSTYL="${LINE:-━}"
	print_c "$TITLE" "$LSTYL"
	PS3=$(print_c "$LSTYL" "$LSTYL" ; echo "$2")
	select SL in ${LIST}; do
		[[ -n $SL ]] && MV+="$SL " || return
	done
}

#LI=$(ls --group-directories-first ${HOME})
#multilist "$LI" "Please select multible, q to go back: " " This is your Home Dir "
#echo
#echo "$MV"
